# Generated by Django 3.1.3 on 2021-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210310_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
    ]
