# Generated by Django 3.1.3 on 2021-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acvitation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_listing',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
