# Generated by Django 3.1.3 on 2021-03-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210311_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='acvitation',
            new_name='activation',
        ),
    ]
