# Generated by Django 3.1.3 on 2021-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210311_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
