# Generated by Django 3.1.3 on 2021-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='listings',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
